### ISSUE TITLE
求 ExtremeSoundMuffler Localizable

### ISSUE THREAD

**Issue by Kasualix** [TexTrueStudio/.github#1]
[万恶之源](https://github.com/LeoBeliik/ExtremeSoundMuffler/blob/d0d9700f531cd0f7fef6fa593d2a830ec63ce0db/src/main/java/com/leobeliik/extremesoundmuffler/utils/Tips.java#L5)
qwq

**Comment by TexBlock** [comment]
草，你怎么搁着发issue

**Comment by Kasualix** [comment]
当时脑子一抽（
